apiVersion: v1
kind: Namespace
metadata:
  name: students
  labels:
    name: students
    purpose: cyber-range-labs
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: student-isolation
  namespace: students
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: student-quota
  namespace: students
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    count/pods: "10"
    count/services: "5"
    count/persistentvolumeclaims: "2" 