all:
  children:
    proxmox:
      hosts:
        proxmox-node:
          ansible_host: 192.168.1.108        # Адрес хоста Proxmox
          ansible_user: root                # Пользователь Proxmox (root)
    k8s_cluster:
      children:
        k8s_master:
          hosts:
            k8s-master-1:
              ansible_host: 192.168.10.10   # Первый master-нода k8s кластер
            k8s-master-2:
              ansible_host: 192.168.10.11   # Второй master-нода
            k8s-master-3:
              ansible_host: 192.168.10.12   # Третий master-нода
        k8s_workers:
          hosts:
            k8s-worker-1:
              ansible_host: 192.168.10.20   # Первый worker-нода
            k8s-worker-2:
              ansible_host: 192.168.10.21   # Второй worker-нода
            k8s-worker-3:
              ansible_host: 192.168.10.22   # Третий worker-нода
